name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Build and Package
        run: |
          cargo install cargo-packager --locked
          cargo build --release
          cargo packager --release

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/packager/*.deb
            target/release/packager/*_x86_64.tar.gz

      - name: Publish to AUR
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        run: |
          ./.github/scripts/publish-aur.sh ${{ github.ref_name }}
